# What is NumPy?
- It is multi-dimensional array libray.

# How are lists different from NumPy?
- Lists are slow
- NumPy is very fast

# Why NumPy is faster
- Faster to read less bytes of memory .
- No type checking when iterating through objects.
- It has fixed type
- It uses contiguous memory

# Applications of NumPy Library
1. Matlab Replacement
2. Plotting
3. Machine Learning

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimensions of your array
a.ndim

1

In [7]:
b.ndim

2

In [8]:
# Get Shape
a.shape

(3,)

In [10]:
b.shape # because it has two rows and three columns

(2, 3)

In [11]:
# Get Type
a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('float64')

In [14]:
# Get Size
a.itemsize

8

In [15]:
b.itemsize

8

In [16]:
# Get total size
a.nbytes

24

In [17]:
# Get number of elements
a.size

3