# What is NumPy?
- It is multi-dimensional array libray.

# How are lists different from NumPy?
- Lists are slow
- NumPy is very fast

# Why NumPy is faster
- Faster to read less bytes of memory .
- No type checking when iterating through objects.
- It has fixed type
- It uses contiguous memory

# Applications of NumPy Library
1. Matlab Replacement
2. Plotting
3. Machine Learning

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# Get Dimensions of your array
a.ndim

1

In [7]:
b.ndim

2

In [8]:
# Get Shape
a.shape

(3,)

In [10]:
b.shape # because it has two rows and three columns

(2, 3)

In [11]:
# Get Type
a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('float64')

In [14]:
# Get Size
a.itemsize

8

In [15]:
b.itemsize

8

In [16]:
# Get total size
a.nbytes

24

In [17]:
# Get number of elements
a.size

3

# Accessing/Changing specific elements, rows, columns, etc

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
a.shape

(2, 7)

In [25]:
# Get a specific element [row,column]
print(a[1,2])

10


In [29]:
# Get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [32]:
# Get a specific column
print(a[:,2])

[ 3 10]


In [39]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [40]:
a[1,5] = 20

In [41]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [44]:
a[:,2] = 5

In [45]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

# 3-D EXAMPLE

In [51]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
# Get specific element 
print(b[1,0,1])

6


In [54]:
print(b[0,1,1])

4


In [56]:
print(b[:,1,:])

[[3 4]
 [7 8]]


In [57]:
print(b[:,0,:])

[[1 2]
 [5 6]]


In [59]:
print(b[:,0,0])

[1 5]


In [64]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [66]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
# All 1s matrix
np.ones((3,8),dtype='int')

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [73]:
# Any other number np.full((shape),number)
np.full((4,4),99,dtype='float32')

array([[99., 99., 99., 99.],
       [99., 99., 99., 99.],
       [99., 99., 99., 99.],
       [99., 99., 99., 99.]], dtype=float32)

In [80]:
# Any other number (full_like)
np.full_like(a,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [83]:
# Random decimal numbers
np.random.rand(2,2)

array([[0.11929663, 0.74446419],
       [0.71006001, 0.03321281]])

In [90]:
np.random.random_sample(a.shape)

array([[0.94014478, 0.387767  , 0.22631449, 0.34497646, 0.06845131,
        0.43854246, 0.64537943],
       [0.78092895, 0.45381582, 0.38865855, 0.38367858, 0.80899043,
        0.19676731, 0.64553521]])